apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-jwt.fullname" . }}-data
  labels:
    {{- include "postgres-jwt.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage | quote }}
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName | quote }}
  {{- end }}
